### PR TITLE
Allow rendering of fragments directly from spring controllers

### PR DESCRIPTION
**Pull request by Antibrumm**
- "home/welcome" -> normal template
- "home/welcome :: message" -> ajax fragment Name selector
- "home/welcome :: [//messagenode]" -> ajax fragment DOM selector

### CODE REVIEW

**Comment by Antibrumm** [comment]
I have read (https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.0.16/CONTRIBUTING.markdown) and
I agree to the Terms & Conditions of Thymeleaf as specified in the above link.

**Comment by danielfernandez** [comment]
Hi. I suppose "Antibrumm" and "Martin Frey" are the same person :-)

I like your idea, I think this could go into Thymeleaf 2.1. Nevertheless, I'd prefer a different implementation. Let me explain my idea:

In my opinion, the code for creating an `IFragmentSpec` is too manual, and it depends quite a lot on repeating parsing structures that are in fact contained in the `StandardFragmentProcessor.computeStandardFragmentSpec(...)` method. So I think what we should do is:
- Leave `ThymeleafViewResolver` without any modifications. If viewName is in the form `template :: fragment`, just set it like that as the `ThymeleafView`'s object `templateName` property. This will allow developers to declare specific configurations for fragmentary view names in the form of Spring beans initialized by means of the `beanFactory.configureBean(...)/initializeBean(...)` calls: we can have one bean for `template`, another bean for `template :: frag1`, etc. Of course all of this would be optional as it is today.
- Use `StandardFragmentProcessor.computeStandardFragmentSpec(...)` at the `ThymeleafView` class in order to obtain an (optional) `IFragmentSpec` object to be used. This method needs a `Configuration` object (which can be obtained with `templateEngine.getConfiguration()`, as well as the name of the attribute to be searched for fragment names (usually `th:fragment`). Also an `IProcessingContext` object will be needed, which can be obtained by creating an instance of `ProcessingContext` with `new ProcessingContext(IContext)`. Then the `templateEngine.process(...)` method to be used would be the one that receives an `IProcessingContext` instead of an `IContext`.

Advantages of this approach:
- Exactly the same parsing mechanism would be used in `th:include` / `th:substituteby` and in view names. This way every new feature added to the standard fragment specification format would be automatically made available at view names.
- Using `StandardFragmentProcessor.computeStandardFragmentSpec(...)` would allow developers to use _standard expressions_  in view names, like `${myTemplate.name} :: ${fragmentName}`or even simply `${myTemplate.name}`. These expressions would be executed against the same processing context (`IContext`) used for executing the template itself.

What do you think? Do you see any caveats in this approach? Would you be able to write a new pull request for this?

**Comment by danielfernandez** [comment]
Updated 2.1.0-SNAPSHOT.

Now controllers can specify views like `viewName :: fragment` or even `viewName :: //table.content`, taking full advantage of the new DOM Selector syntax.

Besides, parameters can also be used for `th:fragment` specifications (always named), like: `viewName :: fragment (p0='oneparam',p1='twoparam')`

**Comment by Antibrumm** [comment]
Thumbs up. Funny enough i just pulled thymeleaf 2.1-dev this day and wanted to do something on it but failed because i was not able to build it. And honestly i wouldn't have implemented it as short as you did. 
Nice work.

**Pull request closed without merging**
