### PR TITLE
Add newline at the beginning of textarea on 2.1.x line

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've fixed gh-103.
Please review.

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thank you for your fix. 

Please, in order to accept your PR I would need you to carefully read our Contribution Terms and Conditions here https://github.com/thymeleaf/thymeleaf-spring/blob/8f2d2373b9a014a530f9f7cd443c92d31829ef4b/CONTRIBUTING.markdown 

Once done, please add a comment in this PR explicitly stating your agreement with these conditions.

**Comment by kazuki43zoo** [comment]
Hi @danielfernandez , I agree with the Thymeleaf ICLA.

**Comment by kazuki43zoo** [comment]
@danielfernandez , thanks for merging!!
I hope to feedback to Thymeleaf 3.x line.

Thanks.

**Comment by danielfernandez** [comment]
Thanks. Don't worry about 3.0, I'll do it myself in a moment… I'm right now in a hurry to release `3.0.0.BETA03` today and I want to be including this.

**Comment by danielfernandez** [comment]
Updated `2.1.5-SNAPSHOT` with this fix.

**Comment by danielfernandez** [comment]
The 2.1 branch is now fully updated.

If you want, I'd be happy to add you as a contributor at http://www.thymeleaf.org/team.html, linking to your GitHub profile. For that, I'd need you to send me an email (my address is listed on that page) confirming the name you want to appear there (Kazuki Shimizu, I suppose), your location (Japan, I suppose) and a personal, non-corporate email address that we can keep for future contact with you.

**Comment by kazuki43zoo** [comment]
Hi @danielfernandez 

> If you want, I'd be happy to add you as a contributor at http://www.thymeleaf.org/team.html, linking to your GitHub profile.

Please adding. My personal profile(name, location, email) is same with the GitHub profile.

**Pull request merged**
