### PR TITLE
Add new attribute for only global errors th:errorsGlobal

### PR DESCRIPTION
**Pull request by lightszentip**
The JSTL form:errors tag display only global Errors. With thymeleaf attribute  errors="*"it  display global errors and field errors.

Now I created a new attribute errorsGlobal that only show global errors without field errors. 

I have create a patch. 
You can use the new attribute with th:errorsGlobal="".

### CODE REVIEW

**Comment by lightszentip** [comment]
I have read (https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.0.16/CONTRIBUTING.markdown) and
I agree to the Terms & Conditions of Thymeleaf as specified in the above link.

**Comment by danielfernandez** [comment]
I understand your point. And you are right that Spring's JSP tags make a difference between _"allErrors"_ and _"globalErrors"_ (which do not include errors linked to specific fields).

However, I don't think adding a new `th:` attribute for such a specific case would be a good idea, and it would be incomplete. I'd prefer this approximation:
- Create new `th:errors="all"` and `th:errors="*"` as a synonim for current `th:errors="*{*}"`.
- Create new `th:errors="global"` for outputting global errors.
- Add new expression utility methods `#fields.hasErrors()` and `#hasAnyErrors()` as a synonim for current `#fields:hasErrors('*')`.
- Add new expression utility methods `#fields.errors()` and `#fields.allErrors()` as a synonim for current `#fields:errors('*')`.
- Add new expression utility methods `#fields.hasGlobalErrors()` and `#fields.globalErrors()` for obtaining global errors --for example, in order to iterate them.

How to do this?
- Add to `FieldUtils.getBindStatus(...)` support for getting global errors: very similar to current support for the `*{*}` value for _all errors_ but not adding the `*` at the end of the expression used for constructing the `BindStatus` object. For the sake of code elegance I recommend substituting the `"*{*}"` constant by `"all"`, and then using a new constant called `"global"`. This `*{*}` --> `all` change of course will require some adjusts at the `FieldUtils` class and also at the implementation of the `th:errors` tag.
- Adding the new methods and possible values to `FieldUtils`, `Fields` and the implementation of `th:errors`.

What do you think? Would you be willing to create a new pull request (including some tests) for this feature? If so, this could go into version 2.1.

**Comment by lightszentip** [comment]
I think your way is better. I will change the code and create a new pull request for this feature.

**Comment by lightszentip** [comment]
@danielfernandez , I have changed my code (https://github.com/lightszentip/thymeleaf-spring3/commits/2.1-dev).

I have got right understand that the methods hasErrors() and hasAnyErrors() doing the same?

And the test files should I add to thymeleaf-tests or to thymeleaf-spring3?

**Comment by danielfernandez** [comment]
Yes, `hasErrors()` and `hasAnyErrors()` should be the same. I just thought both were suitable names in English for representing the same concept.

The test files... if you have created test files for execution with the thymeleaf-testing library, then they go into thymeleaf-tests. If they are normal JUnit tests, then they are OK in thymeleaf-spring3. Eventually all tests in the project will be moved to thymeleaf-tests, but at the moment we are just putting there tests that use the new testing framework.

**Pull request closed without merging**
