### PR TITLE
Set the ApplicationContext to RedirectView to find the RequestDataValueProcessor

### PR DESCRIPTION
**Pull request by ogatakex-zz**
RedirectView#updateTargetUrl to get RequestDataValueProcessor from WebApplicationContext.

### CODE REVIEW

**Comment by danielfernandez** [comment]
For the sake of documentation: this PR would allow the URLs set into `RedirectView`s to be modifed by a registered `RequestDataValueProcessor` instance before the redirect actually takes place.

**Comment by danielfernandez** [comment]
Thanks for your contribution. Your code looks fine to me. Please, in order to merge it, we need you to explicitly accept the Contribution Terms: https://github.com/thymeleaf/thymeleaf-dist/blob/4e2a9da2cfc09a0dd19d624c2733d1a2e20abaa0/CONTRIBUTING.markdown (a comment here will suffice).

**Comment by ogatakex-zz** [comment]
Thank you for your review!
I accept the Contribution Terms.

**Comment by danielfernandez** [comment]
Thank you very much. I've just merged your PR. If you want to be listed at the team page as a contributor ( http://www.thymeleaf.org/team.html ) please send me an email specifying your name, forum ID (if you have one), Location (country) and email (must be a non-corporate one), and I'll be happy to add you there.

**Comment by danielfernandez** [comment]
Updated 2.1.4-SNAPSHOT both for thymeleaf-spring3 and thymeleaf-spring4

**Pull request merged**
