### PR TITLE
#176 Fix FieldUtils.validateBeanPath() to accept paths with a key

### PR DESCRIPTION
**Pull request by arne-vandamme**
Quickfix for https://github.com/thymeleaf/thymeleaf-spring/issues/176
Tests (separate project) still work, did not seem to find specific bind status tests however :/

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks for your contribution. Please note that we would need you to explicitly agree and accept the terms in https://github.com/thymeleaf/thymeleaf-spring/blob/5f6bea3bf24185ba3cb823ea5593a93db3678232/CONTRIBUTING.markdown (a comment here will suffice).

**Comment by arne-vandamme** [comment]
I agree and accept the contributing terms.

**Comment by danielfernandez** [comment]
Already in `3.0.10-SNAPSHOT`

**Comment by danielfernandez** [comment]
@arne-vandamme merged, thanks again.

I'd be happy to add you as a contributor at http://www.thymeleaf.org/team.html if you are OK with that. For that I would list in that page your name and your country (*Arne Vandamme* and *Belgium*), and link to your GitHub profile. Also, I would need you to send me an email (my address is in that page) with a personal, non-corporate email address at which we could reach you in the future.

**Pull request merged**
