### PR TITLE
Fixes #219 - ThymeleafViewResolver and ThymeleafReactiveViewResolver …

### LINKED ISSUE #219: Thymeleaf's redirect view resolver + AspectJ leaks memory
This issue is very similar to the now fixed issue https://github.com/spring-projects/spring-framework/issues/21583 .

Andy Wilkinson: 
> In short, the problem is that InternalResourceViewResolver calls AutowireCapableBeanFactory.initializeBean(Object existingBean, String beanName) using the complete URL as the beanName. The bean name is then used by AbstractAutoProxyCreator.wrapIfNecessary(Object, String, Object) as the key when it caches the fact that no advice applies to it. When the possible redirect URLs are unbounded this leads to an unbounded number of entries being added to the cache.

In this case is [`ThymeleafViewResolver`](https://github.com/thymeleaf/thymeleaf-spring/blob/3.0-master/thymeleaf-spring5/src/main/java/org/thymeleaf/spring5/view/ThymeleafViewResolver.java#L779), not `InternalResourceViewResolver`.

Juergen Hoeller commented

> AbstractAutoProxyCreator is fundamentally right to make assumptions about the bean name: The supplied name should identify the kind of bean, not the individual instance. From that perspective, it's wrong for RedirectView to use the specified URL as bean name (as per #13413 when this was introduced); I've changed it to use the redirect prefix ("redirect:") to identify this kind of bean. Being at it, as of 5.1, we're also using the forward prefix ("forward:") for forward views (InternalResourceView) now, sending those through applyLifecycleMethods as well (even if just for the optional bean name and application context there since it may help for tracking).

Steps to reproduce:
* Run the program (see attached)
* Make many requests to it (e.g. with apache benchmark `ab -n 200000 -c 100 http://localhost:8080/` )
* Check that the heap memory goes up and doesn't come down after doing a manual GC
image

* Or check with the debugger that the map AnnotationAwareAspectJAutoProxyCreator.advisedBeans contains thousands of entries
image

[Thymeleaf-AspectJ.zip](https://github.com/thymeleaf/thymeleaf-spring/files/3718525/Thymeleaf-AspectJ.zip)

### PR DESCRIPTION
**Pull request by DamianFekete**
…expose redirect prefix as bean name

### CODE REVIEW

**Comment by DamianFekete** [comment]
@danielfernandez , I've recreated #221 without the POM change (I can't compile it without the pom.xml change).

> please note that we would need you to explicitly agree and accept the terms in https://github.com/thymeleaf/thymeleaf-spring/blob/5f6bea3bf24185ba3cb823ea5593a93db3678232/CONTRIBUTING.markdown (a comment here will suffice)

I agree and accept the linked `Terms and Conditions`.

**Comment by danielfernandez** [comment]
Thymeleaf 3.0.12-SNAPSHOT is actually compiled with JDK11 (in fact Thymeleaf has been built using JDK11 since 3.0.10)… are you trying to compile the current `3.0-dev` branch or an older version? If it is `3.0-dev`, could you show me the errors you are receiving, and specify the JDK build? (the output of `mvn -version` will do)

**Review by danielfernandez — APPROVED** [review]

**Comment by DamianFekete** [comment]
> Thymeleaf 3.0.12-SNAPSHOT is actually compiled with JDK11 (in fact Thymeleaf has been built using JDK11 since 3.0.10)… are you trying to compile the current `3.0-dev` branch or an older version? If it is `3.0-dev`, could you show me the errors you are receiving, and specify the JDK build? (the output of `mvn -version` will do)

@danielfernandez, sorry, I said `compile` (as I built the package last year), but I should have said `package`.

<details>
  <summary><b>mvn -version</b> (I've also tried it with Oracle's JDK 11.0.5)</summary>
<pre>
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: C:\tools\mvn\bin\..
Java version: 11.0.9.1, vendor: Amazon.com Inc., runtime: C:\Program Files\Amazon Corretto\jdk11.0.9_12
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
</pre>
</details>

<details>
  <summary><b>mvn package</b> on the branch 3.0-master => <b>Failure for maven-javadoc-plugin</b></summary>
<pre>
[INFO] --- maven-javadoc-plugin:3.1.0:jar (default) @ thymeleaf-spring5 ---
[INFO] 
Loading source files for package org.thymeleaf.spring5.context...
Loading source files for package org.thymeleaf.spring5.context.webflux...
...
Constructing Javadoc information...
Standard Doclet version 11.0.9.1
Building tree for all the packages and classes...
Generating C:\dev\icc-daimler\thymeleaf-spring\thymeleaf-spring5\target\apidocs\org\thymeleaf\spring5\ISpringTemplateEngine.html...
Generating C:\dev\icc-daimler\thymeleaf-spring\thymeleaf-spring5\target\apidocs\org\thymeleaf\spring5\ISpringWebFluxTemplateEngine.html...
...
Generating C:\dev\icc-daimler\thymeleaf-spring\thymeleaf-spring5\target\apidocs\org\thymeleaf\spring5\view\ThymeleafViewResolver.html...
Generating C:\dev\icc-daimler\thymeleaf-spring\thymeleaf-spring5\target\apidocs\org\thymeleaf\spring5\view\reactive\ThymeleafReactiveView.html...
1 error
100 warnings
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.297 s
[INFO] Finished at: 2020-12-04T09:47:48+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (default) on project thymeleaf-spring5: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: warning - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] javadoc: warning - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
...
[ERROR] javadoc: warning - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] javadoc: error - An internal exception has occurred. 
[ERROR] 	(com.sun.tools.javac.code.Symbol$CompletionFailure: class file for reactor.core.publisher.Mono not found)
[ERROR] Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR] (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
[ERROR] for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] com.sun.tools.javac.code.Symbol$CompletionFailure: class file for reactor.core.publisher.Mono not found
[ERROR] 
[ERROR] Command line was: "C:\Program Files\Amazon Corretto\jdk11.0.9_12\bin\javadoc.exe" --no-module-directories @options @packages
</pre>
</details>

**Comment by danielfernandez** [comment]
Maybe this is some issue in Amazon Coretto's `javadoc` tool, that perhaps was also present in `11.0.5` for Oracle's JDK.

Thymeleaf's official artifacts are currently being built (including javadoc) with:
```
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T19:49:05Z)
Maven home: /home/releases/Software/apache-maven-3.5.3
Java version: 11.0.9, vendor: AdoptOpenJDK
Java home: /home/releases/Software/jdk-11.0.9+11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1029-aws", arch: "amd64", family: "unix"
```

And in my local system:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.9.1, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

Compilation, javadoc and package work perfectly fine in both environments. Maven 3.5.3 is used for official releases instead of 3.6.3 because Maven 3.6 has a nasty bug that makes release deploying hang during HTTP transfer to the central repos.

Maybe you could try with a different JDK build like AdoptOpenJDK's?

**Comment by DamianFekete** [comment]
@danielfernandez , yeah, the last `3.0-master` builds correctly.
I was on the `3.0-master` but I haven't pulled the recent changes from it. The problem was fixed last month in
```
Fixed configuration for the maven-javadoc-plugin
0bcdc176 Daniel Fernández on 15.11.2020 at 14:25
```

> in fact Thymeleaf has been built using JDK11 since 3.0.10

I'm not sure how this worked before, but it doesn't matter anymore.

Thanks for your time and for merging this.

**Pull request merged**
