### PR TITLE
Allow using a custom expression parser

### PR DESCRIPTION
**Pull request by heinzfink**
Hello, this PR solves the issue mentioned in #24 .
A custom expression parser can be used by setting the variable thymeleaf::ExpressionParser.
Maybe someone can have a look at it and give me some feedback?
Thanks and best regards
Heinz

### CODE REVIEW

**Comment by rPraml** [comment]
@danielfernandez is there a chance to get this PR merged & included in the next release?

**Comment by rPraml** [comment]
Hello @danielfernandez, we still have the requirement to set a different expression parser in thymeleaf.
Currently we release our own patched version in our internal repo (every time when there is an update on thymelead)
It would be great, if we get some feedback, if and how to get this PR merged.

**Comment by rPraml** [comment]
I think this branch is obsolete, because development continues here: https://github.com/thymeleaf/thymeleaf/pull/898
@heinzfink  FYI

**Comment by danielfernandez** [comment]
Closing as a result of thymeleaf/thymeleaf#898 being closed without merging.

**Pull request closed without merging**
